services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todoapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  migrate:
    image: migrate/migrate
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:password@db:5432/todoapp?sslmode=disable",
      "up"
    ]
    volumes:
      - ./db/migration:/migrations
    depends_on:
      - db
    networks:
      - app-network

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=config/config.yaml
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
